/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { inputType } from "./components/types/import.types";
export { inputType } from "./components/types/import.types";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WcInput {
        "disabled": boolean;
        "label": string;
        "type": inputType;
    }
    interface WcTextarea {
        "cols": number;
        "rows": number;
        "value": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWcInputElement extends Components.WcInput, HTMLStencilElement {
    }
    var HTMLWcInputElement: {
        prototype: HTMLWcInputElement;
        new (): HTMLWcInputElement;
    };
    interface HTMLWcTextareaElement extends Components.WcTextarea, HTMLStencilElement {
    }
    var HTMLWcTextareaElement: {
        prototype: HTMLWcTextareaElement;
        new (): HTMLWcTextareaElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "wc-input": HTMLWcInputElement;
        "wc-textarea": HTMLWcTextareaElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WcInput {
        "disabled"?: boolean;
        "label"?: string;
        "type"?: inputType;
    }
    interface WcTextarea {
        "cols"?: number;
        "rows"?: number;
        "value"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "wc-input": WcInput;
        "wc-textarea": WcTextarea;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "wc-input": LocalJSX.WcInput & JSXBase.HTMLAttributes<HTMLWcInputElement>;
            "wc-textarea": LocalJSX.WcTextarea & JSXBase.HTMLAttributes<HTMLWcTextareaElement>;
        }
    }
}
